<?php

return array(
  'fieldbasedacls_acl_is_enabled' => array(
    'group_name' => 'Field Based ACLS',
    'group' => 'fieldbasedacls',
    'name' => 'fieldbasedacls_acl_is_enabled',
    'type' => 'Boolean',
    'default' => 1,
    'add' => '4.2',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'FieldBased ACL is enabled',
    'help_text' => 'Should field-based ACLs be enabled for this site',
  ),
  'fieldbasedacls_acl_grant_table' => array(
    'group_name' => 'Field Based ACLS',
    'group' => 'fieldbasedacls',
    'name' => 'fieldbasedacls_acl_grant_table',
    'type' => 'Integer',
    'default' => null,
    'add' => '4.2',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Custom Group to grant permissions',
    'help_text' => 'Setting values in this table will give people ability to see others',
  ),
  'fieldbasedacls_acl_to_table' => array(
    'group_name' => 'Field Based ACLS',
    'group' => 'fieldbasedacls',
    'name' => 'fieldbasedacls_acl_to_table',
    'type' => 'Integer',
    'default' => null,
    'add' => '4.2',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Custom Group for what permissions with access',
    'help_text' => 'Setting values in this table will determine the contact\'s visibility',
  ),
  'fieldbasedacls_acl_field_label_map' => array(
    'group_name' => 'Field Based ACLS',
    'group' => 'fieldbasedacls',
    'name' => 'fieldbasedacls_acl_field_label_map',
    'type' => 'Array',
    'default' => null,
    'add' => '4.2',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Fields to map, permission table field label as keys & to field name as values',
    'help_text' => 'The label will be parsed through a like clause surrounded by % in the fields',
  ),
 );
